### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by CnrDmr** [alperozisik/fantasygrounds-turkish-font#1]
.ext dosyasını doğru yere koymama rağmen beceremedim olmuyor. Program yüklüyor extension'ı chat box'a yazıyor türk bayrağı koymuşsun o çıkıyor. Ama ı,ğ,ş harflerini yazamıyorum chat'e

**Comment by alperozisik** [comment]
Merhaba,
Belki sende başka font'larda yüklü olabilir mi? (Onlar seçili olmasın)

Bendeki ekran görüntülerini paylaşıyorum


![main](https://user-images.githubusercontent.com/7248325/48301352-8db35880-e4fd-11e8-8eef-690966bdc5d3.PNG)

![game](https://user-images.githubusercontent.com/7248325/48301355-986ded80-e4fd-11e8-826a-3f9d13e565bf.PNG)

**Comment by alperozisik** [comment]
@CnrDmr, paylaştığın bilgiler ile sorunu üretip çözemiyorum

**Comment by CnrDmr** [comment]
12pt Clear Font diye bi extension kullanıyorum normalde ama onu aktive etmediğimde de işlemiyor. 
Macbook üzerinden Wine adlı bi windows emulatörü üzerinden oynuyorum oyunu bi etkisi var mı bilmiyorum. Font'u indirip bilgisayarın font kütüphanesine de kaydettim ama ı İ ğĞ şŞ harflerini alamıyorum

**Comment by CnrDmr** [comment]
.ext dosyasıyla da denedim .zip'in açılmış hali klasörleri koyarak da

**Comment by alperozisik** [comment]
Başka bir font extension'u çakışma yaratabilir. Kullanmamanı tavsiye ederim. Sadece ext dosyasını ilgili klasöre koyman yeterli. Sistem fontu ya da zip'i extract etmek işine yaramaz.
Eğer İlk ekran görüntüsündeki gibi seçip açtığında bayrağı görüyorsan, o zaman bu Türkçe extension yüklenmiştir. Tavsiyem diğer bütün seçenekleri kaldır, sadece bununla aç ve dene. Eğer sırf Türkçe ile açtığında işini görüyorsan, demekki yapmışsındır ve asıl sorun diğer extension'ların çakışmasından kaynaklıdır.
Daha önceden MacOS ile denedim diye hatırlıyorum; ama emin değilim. Önümüzdeki hafta kontrol ederim sorun devam ederse

**Comment by CnrDmr** [comment]
Sadece bu Turkish.ext aktive edip denememe rağmen alamıyorum türkçe harfleri. Oyunu yüklediğimde bayrağı görüyorum yani extension'ı yüklemekte sorun yok, hata penceresi gelmiyor. Ama ı İ Ğğ şŞ harfleri çıkmıyor buna rağmen.

**Comment by CnrDmr** [comment]
Sonunda deneme fırsatım oldu. Ext Windows'ta Steam üzerinden FG demo indirip denedim, gayet düzgün çalışıyor bütün harfler sıkıntısız.

Mac'te olduğum için sorun yani sanırım. Font dosyalarının uzantısıyla mı alakalı acaba?
